# frozen_string_literal: true

# Example pattern for Advantest 93K
Pattern.create do
  ss 'Test pattern generated by Origen'
  ss 'Pattern: example_pattern'
  ss "Version: #{TestProgram::VERSION}"
  ss "Date: #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}"

  # Initialize DUT
  $dut.reset_device

  # Test sequence
  ss '--- Write Test ---'
  10.times do |i|
    $dut.write_data(i)
  end

  ss '--- Read Test ---'
  10.times do |i|
    $dut.read_data(i)
  end

  ss '--- Pattern Complete ---'
end
