AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'output/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

# Style preferences
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

# Allow global variables (Origen framework convention for $dut)
Style/GlobalVars:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'pattern/**/*'
